### ISSUE TITLE
Dockerize the CLI tool

### ISSUE THREAD

**Issue by niconoe** [timrobertson100/frictionless-transforms#2]
- Would make running the script easier for users without a proper Python/Virtualenv setup
- Good exercise for me :)

**Comment by timrobertson100** [comment]
Yes, very much so. Thank you.

**Comment by niconoe** [comment]
We now have a basic Dockerfile for `ft` and and helper bash script to run it. We can probably easily write a second bash script to run `f2sqlite` (same image, just override the entrypoint)
