### ISSUE TITLE
Create a second CLI tool that only performs the datapackage -> sqlite conversion

### ISSUE THREAD

**Issue by niconoe** [timrobertson100/frictionless-transforms#3]
- Can be handy to debug SQL transformation for the `ft` tool
- Would basically provide https://github.com/niconoe/DarwinSQL/issues/4 for free
- Name: `f2sqlite`? maybe @peterdesmet has a better one?

**Comment by peterdesmet** [comment]
Yes, especially when creating the SQL conversion, I don't want to reload the initial data package every time, but start from a saved SQLite DB, so I would really like 2 CLI comments.

**Comment by niconoe** [comment]
@peterdesmet : there's now a basic `f2sqlite` script:

`$ f2sqlite ./sample_input_packages/periodic-table/datapackage.json periodic-table.sqlite3`

After pulling the code, you'll need to run (only once):

`$ pip install -e .`

so your system knows about the new script.

**Comment by niconoe** [comment]
Now also available via Docker. Closing this, open new issues for specific bug fixes or feature requests.
